language: python
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - nosetests --with-coverage tests/test_user.py
  - nosetests --with-coverage tests/test_business.py
  - nosetests --with-coverage tests/test_review.py

after_success:
  -coverage report
  -coveralls
  #upload reports to coveralls.io

