language: python
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

# command to run tests
script:
  - pytest tests/test_user.py
  - pytest tests/test_business.py
  - pytest tests/test_review.py

after_success:
  -coverage report
  -coveralls
  #upload reports to coveralls.io

