language: python
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest testsv2/test_user.py
  - pytest testsv2/test_business.py
  - pytest testsv2/test_review.py

before_script:
  - python manage.py db migrate
  - python manage.py db upgrade

after_success:
  -coverage report
  -coveralls
  #upload reports to coveralls.io

