language: python
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install coverage
  - pip install coveralls
  - pip install pytest-cov
  - pip install -r requirements.txt

# command to run tests
script: pytest --cov tests

after_success:
  -coverage report
  -coveralls
  #upload reports to coveralls.io

