language: python
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - nosetests --with-xcoverage --cover-tests/test_user
  - nosetests --with-xcoverage --cover-tests/test_business
  - nosetests --with-xcoverage --cover-tests/test_review

after_success:
  -coverage report
  -coveralls
  #upload reports to coveralls.io

