language: python
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE tests;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'brian';" -U postgres

# command to run tests
script:
  - pytest testsv2/test_user.py
  - pytest testsv2/test_business.py
  - pytest testsv2/test_review.py

after_success:
  -coverage report
  -coveralls
  #upload reports to coveralls.io

