language: python
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

# command to run tests
script:
  - py.test testsv2/test_user.py
  - py.test testsv2/test_business.py
  - py.test testsv2/test_review.py

after_success:
  -coverage report
  -coveralls
  #upload reports to coveralls.io

