language: python
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt

# Add service
services:
  - postgresql

before_script:
  - psql -c 'create database tests;' -U postgres

# command to run tests
script:
  - pytest
  - coverage run --source='.' manage.py test
  - coverage report

after_script:
  - codeclimate-test-reporter

after_success:
  - coveralls
  #upload reports to coveralls.io

