"""empty message

Revision ID: 39117f9902e0
Revises: 
Create Date: 2018-03-24 18:19:42.940238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39117f9902e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('business', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'date_modified')
    op.drop_column('business', 'date_created')
    # ### end Alembic commands ###
