"""empty message

Revision ID: 9d615d8dcf88
Revises: 39117f9902e0
Create Date: 2018-03-24 20:12:00.726362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d615d8dcf88'
down_revision = '39117f9902e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('business', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'date_modified')
    op.drop_column('business', 'date_created')
    # ### end Alembic commands ###
