"""empty message

Revision ID: c18507ccf4b1
Revises: ed23800f8705
Create Date: 2018-04-01 10:26:25.806679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c18507ccf4b1'
down_revision = 'ed23800f8705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('contact_number', sa.FLOAT(), nullable=True))
    op.drop_column('business', 'business_nominal_capital')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('business_nominal_capital', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('business', 'contact_number')
    # ### end Alembic commands ###
