"""empty message

Revision ID: eabff477b1da
Revises: ecad21fc36fa
Create Date: 2018-03-24 23:45:47.151575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabff477b1da'
down_revision = 'ecad21fc36fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('blacklist_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'blacklist_time')
    # ### end Alembic commands ###
