"""empty message

Revision ID: ed23800f8705
Revises: b17a7f411bf9
Create Date: 2018-03-25 16:00:58.295487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed23800f8705'
down_revision = 'b17a7f411bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('blacklist', sa.Boolean(), nullable=True))
    op.add_column('token', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('token', sa.Column('token_owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'token', 'user', ['token_owner_id'], ['user_id'])
    op.drop_column('token', 'blacklisted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('blacklisted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.drop_column('token', 'token_owner_id')
    op.drop_column('token', 'created_at')
    op.drop_column('token', 'blacklist')
    # ### end Alembic commands ###
